[project]
name = "live2dproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "arcade>=3.3.3",
    "mediapipe==0.10.9",
    "numpy>=2.2.6",
    "opencv-python>=4.11.0.86",
    "protobuf<4",
    "pygame>=2.6.1",
]
